//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 09:49:56 PM EDT 
//


package com.beercom.beerxml.xml;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Grain Record Type
 * 
 * <p>Java class for GrainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GrainType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:beerxml:fermentable:v2}FermentableBase">
 *       &lt;sequence>
 *         &lt;element name="yield_dry_basis">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fine_grind" type="{urn:beerxml:unit:v2}PercentType"/>
 *                   &lt;element name="coarse_grind" type="{urn:beerxml:unit:v2}PercentType" minOccurs="0"/>
 *                   &lt;element name="fine_coarse_difference" type="{urn:beerxml:unit:v2}PercentType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="notes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="moisture" type="{urn:beerxml:unit:v2}PercentType" minOccurs="0"/>
 *         &lt;element name="diastatic_power" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="protein" type="{urn:beerxml:unit:v2}PercentType" minOccurs="0"/>
 *         &lt;element name="soluble_nitrogen_ratio" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="max_in_batch" type="{urn:beerxml:unit:v2}PercentType" minOccurs="0"/>
 *         &lt;element name="recommend_mash" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="potential" type="{urn:beerxml:unit:v2}DensityType" minOccurs="0"/>
 *         &lt;element name="inventory" type="{urn:beerxml:unit:v2}MassType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GrainType", namespace = "urn:beerxml:fermentable:v2", propOrder = {
    "yieldDryBasis",
    "notes",
    "moisture",
    "diastaticPower",
    "protein",
    "solubleNitrogenRatio",
    "maxInBatch",
    "recommendMash",
    "potential",
    "inventory"
})
public class GrainType
    extends FermentableBase
{

    @XmlElement(name = "yield_dry_basis", required = true)
    protected GrainType.YieldDryBasis yieldDryBasis;
    protected String notes;
    protected BigDecimal moisture;
    @XmlElement(name = "diastatic_power")
    protected BigDecimal diastaticPower;
    protected BigDecimal protein;
    @XmlElement(name = "soluble_nitrogen_ratio")
    protected BigDecimal solubleNitrogenRatio;
    @XmlElement(name = "max_in_batch")
    protected BigDecimal maxInBatch;
    @XmlElement(name = "recommend_mash")
    protected Boolean recommendMash;
    protected DensityType potential;
    protected MassType inventory;

    /**
     * Gets the value of the yieldDryBasis property.
     * 
     * @return
     *     possible object is
     *     {@link GrainType.YieldDryBasis }
     *     
     */
    public GrainType.YieldDryBasis getYieldDryBasis() {
        return yieldDryBasis;
    }

    /**
     * Sets the value of the yieldDryBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrainType.YieldDryBasis }
     *     
     */
    public void setYieldDryBasis(GrainType.YieldDryBasis value) {
        this.yieldDryBasis = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the moisture property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMoisture() {
        return moisture;
    }

    /**
     * Sets the value of the moisture property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMoisture(BigDecimal value) {
        this.moisture = value;
    }

    /**
     * Gets the value of the diastaticPower property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiastaticPower() {
        return diastaticPower;
    }

    /**
     * Sets the value of the diastaticPower property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiastaticPower(BigDecimal value) {
        this.diastaticPower = value;
    }

    /**
     * Gets the value of the protein property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProtein() {
        return protein;
    }

    /**
     * Sets the value of the protein property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProtein(BigDecimal value) {
        this.protein = value;
    }

    /**
     * Gets the value of the solubleNitrogenRatio property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSolubleNitrogenRatio() {
        return solubleNitrogenRatio;
    }

    /**
     * Sets the value of the solubleNitrogenRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSolubleNitrogenRatio(BigDecimal value) {
        this.solubleNitrogenRatio = value;
    }

    /**
     * Gets the value of the maxInBatch property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxInBatch() {
        return maxInBatch;
    }

    /**
     * Sets the value of the maxInBatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxInBatch(BigDecimal value) {
        this.maxInBatch = value;
    }

    /**
     * Gets the value of the recommendMash property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRecommendMash() {
        return recommendMash;
    }

    /**
     * Sets the value of the recommendMash property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRecommendMash(Boolean value) {
        this.recommendMash = value;
    }

    /**
     * Gets the value of the potential property.
     * 
     * @return
     *     possible object is
     *     {@link DensityType }
     *     
     */
    public DensityType getPotential() {
        return potential;
    }

    /**
     * Sets the value of the potential property.
     * 
     * @param value
     *     allowed object is
     *     {@link DensityType }
     *     
     */
    public void setPotential(DensityType value) {
        this.potential = value;
    }

    /**
     * Gets the value of the inventory property.
     * 
     * @return
     *     possible object is
     *     {@link MassType }
     *     
     */
    public MassType getInventory() {
        return inventory;
    }

    /**
     * Sets the value of the inventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link MassType }
     *     
     */
    public void setInventory(MassType value) {
        this.inventory = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fine_grind" type="{urn:beerxml:unit:v2}PercentType"/>
     *         &lt;element name="coarse_grind" type="{urn:beerxml:unit:v2}PercentType" minOccurs="0"/>
     *         &lt;element name="fine_coarse_difference" type="{urn:beerxml:unit:v2}PercentType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fineGrind",
        "coarseGrind",
        "fineCoarseDifference"
    })
    public static class YieldDryBasis {

        @XmlElement(name = "fine_grind", namespace = "urn:beerxml:fermentable:v2", required = true)
        protected BigDecimal fineGrind;
        @XmlElement(name = "coarse_grind", namespace = "urn:beerxml:fermentable:v2")
        protected BigDecimal coarseGrind;
        @XmlElement(name = "fine_coarse_difference", namespace = "urn:beerxml:fermentable:v2")
        protected BigDecimal fineCoarseDifference;

        /**
         * Gets the value of the fineGrind property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getFineGrind() {
            return fineGrind;
        }

        /**
         * Sets the value of the fineGrind property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setFineGrind(BigDecimal value) {
            this.fineGrind = value;
        }

        /**
         * Gets the value of the coarseGrind property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCoarseGrind() {
            return coarseGrind;
        }

        /**
         * Sets the value of the coarseGrind property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCoarseGrind(BigDecimal value) {
            this.coarseGrind = value;
        }

        /**
         * Gets the value of the fineCoarseDifference property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getFineCoarseDifference() {
            return fineCoarseDifference;
        }

        /**
         * Sets the value of the fineCoarseDifference property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setFineCoarseDifference(BigDecimal value) {
            this.fineCoarseDifference = value;
        }

    }

}
