//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 09:49:56 PM EDT 
//


package com.beercom.beerxml.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Addition of hops to recipe
 * 
 * <p>Java class for HopAdditionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HopAdditionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="addition" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{urn:beerxml:hop:v2}HopVarietyBase">
 *                 &lt;sequence>
 *                   &lt;element name="form">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="leaf"/>
 *                         &lt;enumeration value="pellet"/>
 *                         &lt;enumeration value="plug"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="use">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="boil"/>
 *                         &lt;enumeration value="dry hop"/>
 *                         &lt;enumeration value="first wort"/>
 *                         &lt;enumeration value="hopback"/>
 *                         &lt;enumeration value="mash"/>
 *                         &lt;enumeration value="continuous boil addition"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="amount" type="{urn:beerxml:unit:v2}MassType"/>
 *                   &lt;element name="time" type="{urn:beerxml:unit:v2}TimeType"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HopAdditionType", namespace = "urn:beerxml:hop:v2", propOrder = {
    "addition"
})
public class HopAdditionType {

    @XmlElement(required = true)
    protected List<HopAdditionType.Addition> addition;

    /**
     * Gets the value of the addition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HopAdditionType.Addition }
     * 
     * 
     */
    public List<HopAdditionType.Addition> getAddition() {
        if (addition == null) {
            addition = new ArrayList<HopAdditionType.Addition>();
        }
        return this.addition;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{urn:beerxml:hop:v2}HopVarietyBase">
     *       &lt;sequence>
     *         &lt;element name="form">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="leaf"/>
     *               &lt;enumeration value="pellet"/>
     *               &lt;enumeration value="plug"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="use">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="boil"/>
     *               &lt;enumeration value="dry hop"/>
     *               &lt;enumeration value="first wort"/>
     *               &lt;enumeration value="hopback"/>
     *               &lt;enumeration value="mash"/>
     *               &lt;enumeration value="continuous boil addition"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="amount" type="{urn:beerxml:unit:v2}MassType"/>
     *         &lt;element name="time" type="{urn:beerxml:unit:v2}TimeType"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "form",
        "use",
        "amount",
        "time"
    })
    public static class Addition
        extends HopVarietyBase
    {

        @XmlElement(namespace = "urn:beerxml:hop:v2", required = true)
        protected String form;
        @XmlElement(namespace = "urn:beerxml:hop:v2", required = true)
        protected String use;
        @XmlElement(namespace = "urn:beerxml:hop:v2", required = true)
        protected MassType amount;
        @XmlElement(namespace = "urn:beerxml:hop:v2", required = true)
        protected TimeType time;

        /**
         * Gets the value of the form property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getForm() {
            return form;
        }

        /**
         * Sets the value of the form property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setForm(String value) {
            this.form = value;
        }

        /**
         * Gets the value of the use property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUse() {
            return use;
        }

        /**
         * Sets the value of the use property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUse(String value) {
            this.use = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link MassType }
         *     
         */
        public MassType getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link MassType }
         *     
         */
        public void setAmount(MassType value) {
            this.amount = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link TimeType }
         *     
         */
        public TimeType getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link TimeType }
         *     
         */
        public void setTime(TimeType value) {
            this.time = value;
        }

    }

}
