//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 09:49:56 PM EDT 
//


package com.beercom.beerxml.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IBUMethodType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IBUMethodType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Rager"/>
 *     &lt;enumeration value="Tinseth"/>
 *     &lt;enumeration value="Garetz"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IBUMethodType", namespace = "urn:beerxml:hop:v2")
@XmlEnum
public enum IBUMethodType {

    @XmlEnumValue("Rager")
    RAGER("Rager"),
    @XmlEnumValue("Tinseth")
    TINSETH("Tinseth"),
    @XmlEnumValue("Garetz")
    GARETZ("Garetz"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    IBUMethodType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IBUMethodType fromValue(String v) {
        for (IBUMethodType c: IBUMethodType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
