//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 09:49:56 PM EDT 
//


package com.beercom.beerxml.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PressureUnitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PressureUnitType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="kPa"/>
 *     &lt;enumeration value="psi"/>
 *     &lt;enumeration value="bar"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PressureUnitType")
@XmlEnum
public enum PressureUnitType {

    @XmlEnumValue("kPa")
    K_PA("kPa"),
    @XmlEnumValue("psi")
    PSI("psi"),
    @XmlEnumValue("bar")
    BAR("bar");
    private final String value;

    PressureUnitType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PressureUnitType fromValue(String v) {
        for (PressureUnitType c: PressureUnitType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
