//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 09:49:56 PM EDT 
//


package com.beercom.beerxml.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VolumeUnitType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VolumeUnitType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ml"/>
 *     &lt;enumeration value="l"/>
 *     &lt;enumeration value="tsp"/>
 *     &lt;enumeration value="tbsp"/>
 *     &lt;enumeration value="ozfl"/>
 *     &lt;enumeration value="cup"/>
 *     &lt;enumeration value="pt"/>
 *     &lt;enumeration value="qt"/>
 *     &lt;enumeration value="gal"/>
 *     &lt;enumeration value="bbl"/>
 *     &lt;enumeration value="iozfl"/>
 *     &lt;enumeration value="ipt"/>
 *     &lt;enumeration value="iqt"/>
 *     &lt;enumeration value="igal"/>
 *     &lt;enumeration value="ibbl"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "VolumeUnitType")
@XmlEnum
public enum VolumeUnitType {

    @XmlEnumValue("ml")
    ML("ml"),
    @XmlEnumValue("l")
    L("l"),
    @XmlEnumValue("tsp")
    TSP("tsp"),
    @XmlEnumValue("tbsp")
    TBSP("tbsp"),
    @XmlEnumValue("ozfl")
    OZFL("ozfl"),
    @XmlEnumValue("cup")
    CUP("cup"),
    @XmlEnumValue("pt")
    PT("pt"),
    @XmlEnumValue("qt")
    QT("qt"),
    @XmlEnumValue("gal")
    GAL("gal"),
    @XmlEnumValue("bbl")
    BBL("bbl"),
    @XmlEnumValue("iozfl")
    IOZFL("iozfl"),
    @XmlEnumValue("ipt")
    IPT("ipt"),
    @XmlEnumValue("iqt")
    IQT("iqt"),
    @XmlEnumValue("igal")
    IGAL("igal"),
    @XmlEnumValue("ibbl")
    IBBL("ibbl");
    private final String value;

    VolumeUnitType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VolumeUnitType fromValue(String v) {
        for (VolumeUnitType c: VolumeUnitType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
